# Generated by Django 5.2.17 on 2026-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(choices=[('CANTEEN', 'CANTEEN'), ('TRANSPORT', 'TRANSPORT'), ('HOSTEL', 'HOSTEL'), ('SPORTS', 'SPORTS'), ('ACADEMIC', 'ACADEMIC'), ('HOSPITALITY', 'HOSPITALITY')], max_length=50),
        ),
    ]
